### ISSUE TITLE
WPML feature?

### ISSUE THREAD

**Issue by whoaloic** [leewillis77/say-what#6]
Hello Lee,
I was wondering, if there is any chance in the future to add WPML compatibily in order to alter strings in multiple languages?
Regards.

**Comment by heinpoblome** [comment]
Hi Lee,

your plugin replaces content with other content.
WPML translates content, but does not really replace it. 
An example : with your plugin I can change the word 'cart' to whatever I want. With WPML I cannot change the original word 'cart', but I can translate it to any word in any language. BUT, the original language of the site can not be changed. That's where your plugin comes in (and does a terrific job at it !).
So, for a multilingual site, where you need to change words in the BASE language, you need both your plugin, and WPML.
Your plugin (as I mentioned in another thread) seems to act 'before' WPML, leading to the situation that WPML no longer translates strings that I have changed with Say What. 
I actually change the word 'cart' into 'enquiry' om my site. And this works great, as long as I stay on the english version of the site. When I go to any other language, the translations do not appear, but instead the replaced string appears, so in my example 'enquiry' instead of the translated word for enquiry.

I mean, for multilingual sites, where you need to change some terms in the base language, a WPML compatible Say What would simply rule the world.

**Comment by leewillis77** [comment]
So you don't need to use Say What? to provide replacements in multiple languages? You just need it to run *after* WPML - so that it only picks up strings that are in the base language?

**Comment by heinpoblome** [comment]
Yes, basically.
WPML has great features that are integrated with Woocommerce and alike. I am guessing that anyone with a multilingual e-commerce site would be using WPML or equivalent to handle the language switching of products, attributes, categories, posts, etcetera. 
Say What? seems to intervene 'before' WPML, somehow messing with the translations. I am not technical enough to explain it to you in IT-language, so this is my deduction of what I see happening. 

Thinking further down the line : when I translate standard stuff of Woocommerce with WPML, for instance 'cart' to 'something that is not cart in another language' it will work as long as there is no update for Woocommerce. Since these are standard terms in Woocommerce every update will 'reset' the basic terms to the original ones. WPML does not handle that (because of compatibility with Woocommerce, as 90% of the websites would expect), but a WPML compatible version of Say What just might. Because then I just put a rule for 'cart', and a rule for 'cart-in-another-language', and these will work regardless of updates (providing, I'm guessing, when Say What? is 'last' in the line). Currently, I would have to adapt WPML translations each time there is an update.

**Comment by leewillis77** [comment]
So - the first thing to try here is to see if re-ordering the filters gets you what you want. I've had a look at Say What, and there's no easy way to change the weight of the filters without editing the plugin right now - but if this works, then I can look at a way of making it easy without modifying the plugin directly. 

In the file say-what-frontend.php there are the following lines:

```php
add_filter( 'gettext', array( $this, 'gettext' ), 10, 3 );
add_filter( 'ngettext', array( $this, 'ngettext' ), 10, 5 );
add_filter( 'gettext_with_context', array( $this, 'gettext_with_context' ), 10, 4 );
add_filter( 'ngettext_with_context', array( $this, 'ngettext_with_context' ), 10, 6 );

```
Try adjusting the “10” in each of those lines to either less than, or greater than 10. My assumption (I don’t use WPML, or have a copy to test with) is that you just need to change whether Say What runs before, or after WPML. Adjusting the “10” should do so, and may give you what you need. 

Let me know how you get on.

**Comment by heinpoblome** [comment]
YES YES YES !!!
It works.
Lowering the value works. I randomly tried lowering it to 5, and it worked. I also tried 20, which did not work.

Brilliant!
The danger here is that I do not really understand what I have been doing, so I will go on and test some more.
The most important flow "shop-cart-checkout" works, and that is the main thing.

A zillion thanks Lee.

**Comment by leewillis77** [comment]
The Pro version of the plugin supports setting different translations in different languages, so closing this.
